### ISSUE TITLE
Added io tests for server.js, now other tests don't run in watch

### ISSUE THREAD

**Issue by mattroid** [notnullgames/boardsocket#2]
I suspect they don't run in watch and in a direct test run. But when running in watch I can see that adding a test.js to the src/server folder causes all the other test to not be picked up by the test runner. 

Any ideas? 

For now I just rename the server test file to run the other tests.

**Comment by konsumer** [comment]
Yeah, watch only picks up the files when it is first run, so it'll need to be restarted. The glob is `src/**/test.js`, so it should run. I'll inspect later, when not on phone.

**Comment by konsumer** [comment]
I noticed the glob might be weird:

```
$ ls src/**/test.js
src/server/test.js
```

```
$ ls src/**/**/test.js
src/components/Board/test.js  src/components/Player/test.js
src/components/Piece/test.js
```

I thought double-asterisk grabs subdirs, recursively, but it seems like it isn't, it's doing the same thing as a single-asterisk.

For cross-platform usage, and making sure the glob does what I think it should, I made a little test-wrapper, since I needed to inject a fake DOM anyway, this doesn't actually add any files, and simplifies the npm scripts a bit.
